package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// Host-specific safety configuration. Every construction here exists because the obvious
// version of it is bypassable; the comments record which bypass.

type guardInput struct {
	Binary     string
	ToolPrefix string
	Blocked    []string
	Approvals  []string
}

type guardFile struct {
	Path    string
	Content string
}

func renderHostConfig(host string, in guardInput) ([]guardFile, error) {
	switch host {
	case "claude-code":
		return claudeCodeConfig(in)
	case "codex":
		return codexConfig(in)
	case "opencode":
		return opencodeConfig(in)
	default:
		return nil, fmt.Errorf("unknown host %q (want claude-code, codex or opencode)", host)
	}
}

// ---------- Claude Code ----------

func claudeCodeConfig(in guardInput) ([]guardFile, error) {
	hook := buildPreToolUseHook(in)

	// Claude Code permission rules are LITERAL PREFIXES, not regular expressions. A pattern
	// like `mcp__.*waba.*_(delete)` matches nothing at all and reads as coverage while
	// providing none — so exact tool names are emitted instead.
	deny := make([]string, 0, len(in.Blocked)*2)
	for _, path := range in.Blocked {
		deny = append(deny, fmt.Sprintf("Bash(%s %s:*)", in.Binary, path))
		deny = append(deny, "mcp__"+in.ToolPrefix+"__"+strings.ReplaceAll(path, " ", "_"))
	}
	// The raw escape hatch is denied per mutating METHOD rather than wholesale, so that a
	// read-only `api GET` remains available.
	for _, method := range apiBlockedMethods {
		deny = append(deny, fmt.Sprintf("Bash(%s api %s:*)", in.Binary, method))
		deny = append(deny, fmt.Sprintf("Bash(%s api %s:*)", in.Binary, strings.ToLower(method)))
	}
	ask := make([]string, 0, len(in.Approvals)*2)
	for _, path := range in.Approvals {
		ask = append(ask, fmt.Sprintf("Bash(%s %s:*)", in.Binary, path))
		ask = append(ask, "mcp__"+in.ToolPrefix+"__"+strings.ReplaceAll(path, " ", "_"))
	}

	settings := map[string]any{
		"permissions": map[string]any{
			"deny": deny,
			"ask":  ask,
		},
		"hooks": map[string]any{
			// Hook *matchers* in settings.json ARE regular expressions, unlike the permission
			// rules above. The two syntaxes differ; mixing them up is how dead config happens.
			"PreToolUse": []any{
				map[string]any{
					"matcher": "^(Bash|mcp__" + in.ToolPrefix + "__.*)$",
					"hooks": []any{
						map[string]any{
							"type":    "command",
							"command": ".claude/hooks/waba-guard.sh",
						},
					},
				},
			},
		},
	}

	raw, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return nil, err
	}
	return []guardFile{
		{Path: ".claude/hooks/waba-guard.sh", Content: hook},
		{Path: ".claude/settings.json", Content: string(raw) + "\n"},
	}, nil
}

// buildPreToolUseHook generates the enforcement script.
//
// The hook, not the permission list, is the thing that actually blocks: permission rules are
// literal prefixes, so `./bin/waba templates delete`, `/usr/local/bin/waba templates
// delete`, `env FOO=1 waba templates delete`, `waba templates de""lete` and
// `true; waba templates delete` all sail past them.
func buildPreToolUseHook(in guardInput) string {
	var b strings.Builder

	b.WriteString(`#!/usr/bin/env bash
# waba-guard.sh — generated by 'waba agent guard'. Do not edit by hand;
# regenerate after adding commands so the rules keep covering the whole tree.
#
# Reads a PreToolUse payload on stdin and exits 2 to DENY, 0 to allow.
set -uo pipefail

payload="$(cat)"

# Extract the fields. Without jq the compact JSON glues the command to its key
# ("command":"waba templates delete"), so the punctuation MUST be flattened to
# whitespace — otherwise the command-position anchor below can never match and this
# branch silently fails open, allowing everything.
if command -v jq >/dev/null 2>&1; then
  tool="$(printf '%s' "$payload" | jq -r '.tool_name // empty')"
  cmd="$(printf '%s' "$payload" | jq -r '.tool_input.command // empty')"
else
  flat="$(printf '%s' "$payload" | tr '\n{}:,' '     ')"
  tool="$(printf '%s' "$flat" | grep -oE '"tool_name" +"[^"]*"' | head -1 | sed 's/.*" *"//; s/"$//')"
  cmd="$(printf '%s' "$flat" | grep -oE '"command" +"[^"]*"' | head -1 | sed 's/.*" *"//; s/"$//')"
fi

deny() {
  printf 'waba-guard: blocked %s\n' "$1" >&2
  exit 2
}

`)

	// MCP tools are matched by exact name: a near-miss like `..._delete2` must stay allowed,
	// so this is equality, not a prefix or substring test.
	b.WriteString("# --- MCP tool names: exact match, so a near-miss like _delete2 is not blocked ---\ncase \"$tool\" in\n")
	for _, path := range in.Blocked {
		b.WriteString("  " + shellCase("mcp__"+in.ToolPrefix+"__"+strings.ReplaceAll(path, " ", "_")) + ") deny \"MCP tool $tool\" ;;\n")
	}
	b.WriteString("esac\n\n")

	b.WriteString(`# --- Bash commands ---
[ -n "$cmd" ] || exit 0

# Normalize before matching: strip the quote and backslash characters an attacker uses to
# split a keyword (de""lete, de\lete) and collapse newlines, so the anchors below see one
# flat line. This is also why a *quoted* blocked command inside an argument
# (rg "waba templates delete" src/) is denied — after quote-stripping the two are
# indistinguishable, and denying is the safe direction.
clean="$(printf '%s' "$cmd" | tr -d '\042\047\134' | tr '\n\r\t' '   ')"

`)

	b.WriteString("for pattern in \\\n")
	for _, path := range in.Blocked {
		b.WriteString("  " + shellQuoteSingle(path) + " \\\n")
	}
	b.WriteString("  ; do\n")

	// The four-part anchored ERE. Each part earns its place:
	//   (^|[;&|(<space>]+)  the command must start a command, not appear mid-word — so
	//                        `mywaba` and `--flag=waba` do not match
	//   ([^[:space:]]*/)?    catches ./bin/waba and /usr/local/bin/waba
	//   <bin><space>+<path>  the command itself
	//   ([[:space:];&|)]|$)  the trailing class MUST accept separators: `waba templates
	//                        delete;true` glues the `;` to the verb, and matching only
	//                        space-or-end-of-line would let that through
	b.WriteString(`  regex="(^|[;&|(&[:space:]]+)([^[:space:]]*/)?` + in.Binary + `[[:space:]]+${pattern}([[:space:];&|)]|$)"
  if printf '%s' "$clean" | grep -Eq "$regex"; then
    deny "command: ${pattern}"
  fi
done

`)

	// The raw escape hatch is matched on the METHOD position specifically, so a GET whose
	// path merely contains "delete" stays allowed while a real DELETE is blocked.
	b.WriteString(`# --- raw API escape hatch: block mutating methods at the METHOD position only, so a
# --- GET whose PATH happens to contain "delete" is still allowed.
api_regex="(^|[;&|(&[:space:]]+)([^[:space:]]*/)?` + in.Binary + `[[:space:]]+api[[:space:]]+([Dd][Ee][Ll][Ee][Tt][Ee]|[Pp][Uu][Tt]|[Pp][Oo][Ss][Tt]|[Pp][Aa][Tt][Cc][Hh])([[:space:];&|)]|$)"
if printf '%s' "$clean" | grep -Eq "$api_regex"; then
  deny "raw api write"
fi

exit 0
`)

	return b.String()
}

// shellCase quotes a literal for a bash case pattern.
func shellCase(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }

// shellQuoteSingle quotes a literal for a bash word list.
func shellQuoteSingle(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }

// ---------- Codex ----------

func codexConfig(in guardInput) ([]guardFile, error) {
	// Codex reads TOP-LEVEL sandbox_mode and approval_policy keys. An invented [sandbox]
	// table parses fine and is then silently ignored, which reads as protection but is none.
	var b strings.Builder
	b.WriteString("# Generated by 'waba agent guard --host codex'.\n")
	b.WriteString("# Regenerate after adding commands so the deny list covers the whole tree.\n\n")
	b.WriteString("sandbox_mode = \"read-only\"\n")
	b.WriteString("approval_policy = \"on-request\"\n\n")
	b.WriteString("# Irreversible operations. Codex has no native per-command deny list, so these are\n")
	b.WriteString("# recorded for the operator and enforced by the read-only sandbox above.\n")
	b.WriteString("# blocked commands:\n")
	for _, p := range in.Blocked {
		fmt.Fprintf(&b, "#   %s %s\n", in.Binary, p)
	}
	return []guardFile{{Path: ".codex/config.toml", Content: b.String()}}, nil
}

// ---------- OpenCode ----------

func opencodeConfig(in guardInput) ([]guardFile, error) {
	// The key is "permission" (singular) with a "bash" sub-map. The plural spelling is
	// ignored without error.
	bash := map[string]string{}
	for _, p := range in.Blocked {
		bash[in.Binary+" "+p+" *"] = "deny"
	}
	for _, method := range apiBlockedMethods {
		bash[in.Binary+" api "+method+" *"] = "deny"
		bash[in.Binary+" api "+strings.ToLower(method)+" *"] = "deny"
	}
	for _, p := range in.Approvals {
		bash[in.Binary+" "+p+" *"] = "ask"
	}
	// Reads stay allowed by default; the explicit entries above take precedence.
	bash[in.Binary+" *"] = "allow"

	cfg := map[string]any{
		"$schema": "https://opencode.ai/config.json",
		"permission": map[string]any{
			"bash": bash,
		},
	}
	raw, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return nil, err
	}
	return []guardFile{{Path: "opencode.json", Content: string(raw) + "\n"}}, nil
}

// ---------- writing ----------

// writeGuardFiles installs the generated files, never overwriting an existing one without
// saying so: a host's settings.json usually holds unrelated user configuration.
func writeGuardFiles(cmd *cobra.Command, o *globalOptions, dir string, files []guardFile) error {
	for _, f := range files {
		path := f.Path
		if dir != "" {
			path = filepath.Join(dir, filepath.Base(f.Path))
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil { // #nosec G703 -- --dir is named by the operator
			return fmt.Errorf("create %s: %w", filepath.Dir(path), err)
		}
		if _, err := os.Stat(path); err == nil {
			backup := path + ".bak"
			existing, err := os.ReadFile(path) // #nosec G304,G703 -- path is the host config location
			if err != nil {
				return fmt.Errorf("read existing %s: %w", path, err)
			}
			if err := os.WriteFile(backup, existing, 0o600); err != nil { // #nosec G703 -- backup beside the file being replaced
				return fmt.Errorf("back up %s: %w", path, err)
			}
			o.note(cmd.ErrOrStderr(), "existing %s backed up to %s", path, backup)
		}

		mode := os.FileMode(0o600)
		if strings.HasSuffix(path, ".sh") {
			mode = 0o700 // the hook has to be executable for the host to run it
		}
		if err := os.WriteFile(path, []byte(f.Content), mode); err != nil { // #nosec G703 -- host config path
			return fmt.Errorf("write %s: %w", path, err)
		}
		fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\n", path)
	}
	return nil
}
