package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerate_WritesTheWholeTree(t *testing.T) {
	dir := t.TempDir()

	n, err := generate(dir)
	require.NoError(t, err)
	assert.Greater(t, n, 100, "the reference should cover the whole command tree")

	root, err := os.ReadFile(filepath.Join(dir, "atlassian.md"))
	require.NoError(t, err)
	assert.Contains(t, string(root), "atlassian")

	// A page per major group, so a resource that stops being registered shows up here.
	for _, page := range []string{"atlassian_issues.md", "atlassian_pages.md", "atlassian_op_call.md"} {
		_, err := os.Stat(filepath.Join(dir, page))
		require.NoErrorf(t, err, "expected a page for %s", page)
	}
}

func TestGenerate_IsDeterministic(t *testing.T) {
	// CI diffs the committed docs against a fresh run, so any per-run variation (cobra's
	// auto-generation date, for one) would make the drift check fail on every commit.
	first, second := t.TempDir(), t.TempDir()
	_, err := generate(first)
	require.NoError(t, err)
	_, err = generate(second)
	require.NoError(t, err)

	a, err := os.ReadFile(filepath.Join(first, "atlassian.md"))
	require.NoError(t, err)
	b, err := os.ReadFile(filepath.Join(second, "atlassian.md"))
	require.NoError(t, err)
	assert.Equal(t, string(a), string(b))

	assert.NotContains(t, string(a), "Auto generated by spf13/cobra on",
		"the generation date must be disabled or every run produces a diff")
}

func TestFixLinks_StripsMarkdownSuffix(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "page.md")
	require.NoError(t, os.WriteFile(path,
		[]byte("See [issues](atlassian_issues.md) and [pages](atlassian_pages.md)."), 0o600))
	// A non-markdown file must be left alone.
	require.NoError(t, os.WriteFile(filepath.Join(dir, "notes.txt"), []byte("keep.md) me"), 0o600))

	n, err := fixLinks(dir)
	require.NoError(t, err)
	assert.Equal(t, 1, n)

	got, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Equal(t, "See [issues](atlassian_issues) and [pages](atlassian_pages).", string(got))
	assert.False(t, strings.Contains(string(got), ".md)"))

	untouched, err := os.ReadFile(filepath.Join(dir, "notes.txt"))
	require.NoError(t, err)
	assert.Equal(t, "keep.md) me", string(untouched))
}

func TestFixLinks_MissingDirectory(t *testing.T) {
	_, err := fixLinks(filepath.Join(t.TempDir(), "absent"))
	require.Error(t, err)
}
